name: "Tests & Linting"

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]

jobs:
  ci-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: install step
        run: npm i
      - name: build
        run: npm run build
      - name: type checking
        run: npm run type-check
      - name: testing
        run: npm run test